# Generated by Django 4.1.7 on 2023-04-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBetAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=50)),
                ('coefficient', models.FloatField()),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
