# Generated by Django 4.1.7 on 2023-04-02 18:42

from django.db import migrations
from django.core.management import call_command


def load_fixtures(state, schema_editor):
    call_command("loaddata", "fixed_data_of_1:1_scores.json")
    call_command("loaddata", "data_of_1:1_scores.json")


def reverse_load_fixtures(state, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_score_bet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_load_fixtures)
    ]
